const map=L.map("map",{zoomControl:false}).setView([35.8,10.7],7);
const base=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"Tiles © Esri"}).addTo(map);
const spots=[[37.0,10.3,"Bizerte"],[36.86,10.34,"Tunis"],[35.83,10.64,"Sousse"],[35.78,10.83,"Monastir"],[35.50,11.06,"Mahdia"],[34.74,10.76,"Sfax"]];
const spotLayer=L.layerGroup().addTo(map);
spots.forEach(p=>L.marker([p[0],p[1]],{icon:L.divIcon({className:"fish-pin",html:"🐟",iconSize:[38,38],iconAnchor:[19,19]})}).bindPopup("<b>🎣 "+p[2]+"</b><br>Zone de pêche recommandée").addTo(spotLayer));
for(let i=0;i<35;i++){const lat=34.7+Math.random()*3,lon=9.6+Math.random()*3.5;L.circleMarker([lat,lon],{radius:2,stroke:false,fillOpacity:.45}).addTo(map)}
document.getElementById("plus").onclick=()=>map.zoomIn();document.getElementById("minus").onclick=()=>map.zoomOut();
const layerNames={wind:"💨 Vent",waves:"〰 Vagues",currents:"⟳ Courants",temp:"♨ Température"};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector(".legend-title").textContent=layerNames[b.dataset.layer]||"Couche";});
const content={weather:["Météo & Mer","Conditions marines en temps réel, vent, vagues et température."],fishing:["Pêche","Consultez les zones recommandées et les conditions pour sortir en mer."],species:["Espèces","Daurade, Loup, Sar et autres espèces recommandées selon les conditions."],zones:["Zones","Explorez les zones de pêche autour de la Tunisie."],forecast:["Prévisions","Prévisions horaires pour organiser votre sortie."],fav:["Favoris","Vos zones et espèces favorites apparaîtront ici."],settings:["Paramètres","Langue, unités, notifications et préférences."]};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");const v=b.dataset.view;document.getElementById("mapView").classList.toggle("hidden",v!=="map");document.getElementById("contentView").classList.toggle("hidden",v==="map");if(v!=="map"){document.getElementById("contentTitle").textContent=content[v][0];document.getElementById("contentText").textContent=content[v][1];document.getElementById("contentGrid").innerHTML=["🌤️ Conditions actuelles","💨 Vent et direction","🌊 État de la mer","🎣 Recommandations"].map(x=>`<div><h2>${x}</h2><p>Module RED LINE FISHING — données prêtes à être connectées aux API.</p></div>`).join("")}});
document.getElementById("arBtn").onclick=()=>{document.documentElement.dir=document.documentElement.dir==="rtl"?"ltr":"rtl";document.documentElement.lang=document.documentElement.lang==="ar"?"fr":"ar";document.getElementById("arBtn").textContent=document.documentElement.lang==="ar"?"FR":"عربي AR"};
